# Focus

This notebooks focus is on checking the data and cleaning data from yFinance

# Imports

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Make sure data and processed directories exist

In [2]:
RAW_DATA_PATH = Path("../../../data/raw/yfinance")
PROCESSED_DATA_PATH = Path("../../../data/processed/source_data/yfinance")

In [3]:

if not RAW_DATA_PATH.exists():
    print(f"Creating directory: {RAW_DATA_PATH}")
    RAW_DATA_PATH.mkdir(parents=True, exist_ok=True)
else:
    print(f"Directory already exists: {RAW_DATA_PATH}")
if not PROCESSED_DATA_PATH.exists():
    print(f"Creating directory: {PROCESSED_DATA_PATH}")
    PROCESSED_DATA_PATH.mkdir(parents=True, exist_ok=True)
else:
    print(f"Directory already exists: {PROCESSED_DATA_PATH}")

Directory already exists: ..\..\data\raw\yfinance
Directory already exists: ..\..\data\processed\yfinance

# Setup Adjusted Close Data

First, I loaded the file normally to inspect its structure. 

Then I reloaded it with the date column as the index so the dataset is easier to use for time-series analysis.

In [4]:
adj_close_0 = pd.read_csv(
    RAW_DATA_PATH / "yfinance_adjusted_close_prices.csv",
)

adj_close_0.head()

,Date,AAPL,AGG,AMZN,CAT,GLD,JPM,KO,LLY,LMT,...,PG,QQQ,SPY,TLT,UNH,V,VNQ,VXUS,VZ,XOM
0,2018-01-02,40.267082,85.275650,59.450500,131.293884,125.150002,85.901283,35.024231,74.897758,254.261307,...,72.280693,150.057236,235.954269,98.342468,191.993912,107.888260,59.645275,44.600651,33.712944,58.185493
1,2018-01-03,40.260067,85.283470,60.209999,131.494553,124.820000,85.988808,34.947315,75.304634,256.392395,...,72.193008,151.515289,237.446762,98.812691,194.007950,108.962296,59.472111,44.911568,33.020172,59.328255
2,2018-01-04,40.447075,85.228775,60.479500,133.300461,125.459999,87.220619,35.439529,75.640739,260.790497,...,72.703293,151.780411,238.447510,98.796982,194.850037,109.367462,58.447609,45.284660,33.127247,59.410366
3,2018-01-05,40.907566,85.174149,61.457001,135.407288,125.330002,86.660713,35.431843,76.569443,263.153229,...,72.751144,153.304703,240.036514,98.514900,198.565582,111.986694,58.476460,45.587811,33.051674,59.362492
4,2018-01-08,40.755634,85.150681,62.343498,138.809982,125.309998,86.788719,35.378010,76.180275,261.939941,...,73.133896,153.901215,240.475464,98.452194,195.119110,112.438942,58.779499,45.564491,32.994991,59.629364

In [5]:
# Make index a datetime index
adj_close = pd.read_csv(
    RAW_DATA_PATH / "yfinance_adjusted_close_prices.csv",
    index_col=0,
    parse_dates=True
)

adj_close.head()

,AAPL,AGG,AMZN,CAT,GLD,JPM,KO,LLY,LMT,MSFT,...,PG,QQQ,SPY,TLT,UNH,V,VNQ,VXUS,VZ,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-02,40.267082,85.275650,59.450500,131.293884,125.150002,85.901283,35.024231,74.897758,254.261307,78.699913,...,72.280693,150.057236,235.954269,98.342468,191.993912,107.888260,59.645275,44.600651,33.712944,58.185493
2018-01-03,40.260067,85.283470,60.209999,131.494553,124.820000,85.988808,34.947315,75.304634,256.392395,79.066170,...,72.193008,151.515289,237.446762,98.812691,194.007950,108.962296,59.472111,44.911568,33.020172,59.328255
2018-01-04,40.447075,85.228775,60.479500,133.300461,125.459999,87.220619,35.439529,75.640739,260.790497,79.762062,...,72.703293,151.780411,238.447510,98.796982,194.850037,109.367462,58.447609,45.284660,33.127247,59.410366
2018-01-05,40.907566,85.174149,61.457001,135.407288,125.330002,86.660713,35.431843,76.569443,263.153229,80.750969,...,72.751144,153.304703,240.036514,98.514900,198.565582,111.986694,58.476460,45.587811,33.051674,59.362492
2018-01-08,40.755634,85.150681,62.343498,138.809982,125.309998,86.788719,35.378010,76.180275,261.939941,80.833374,...,73.133896,153.901215,240.475464,98.452194,195.119110,112.438942,58.779499,45.564491,32.994991,59.629364

In [6]:
adj_close.shape

(2010, 21)

In [7]:
adj_close.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2010 entries, 2018-01-02 to 2025-12-30
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2010 non-null   float64
 1   AGG     2010 non-null   float64
 2   AMZN    2010 non-null   float64
 3   CAT     2010 non-null   float64
 4   GLD     2010 non-null   float64
 5   JPM     2010 non-null   float64
 6   KO      2010 non-null   float64
 7   LLY     2010 non-null   float64
 8   LMT     2010 non-null   float64
 9   MSFT    2010 non-null   float64
 10  NEE     2010 non-null   float64
 11  PG      2010 non-null   float64
 12  QQQ     2010 non-null   float64
 13  SPY     2010 non-null   float64
 14  TLT     2010 non-null   float64
 15  UNH     2010 non-null   float64
 16  V       2010 non-null   float64
 17  VNQ     2010 non-null   float64
 18  VXUS    2010 non-null   float64
 19  VZ      2010 non-null   float64
 20  XOM     2010 non-null   float64
dtypes: float64(21)
memory usage: 345.5 KB

In [8]:
# Check for missing vals
missing_counts = adj_close.isna().sum()
missing_percent = adj_close.isna().mean() * 100

missing_summary = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_percent": missing_percent
}).sort_values("missing_percent", ascending=False)

missing_summary

      missing_count  missing_percent
AAPL              0              0.0
AGG               0              0.0
AMZN              0              0.0
CAT               0              0.0
GLD               0              0.0
JPM               0              0.0
KO                0              0.0
LLY               0              0.0
LMT               0              0.0
MSFT              0              0.0
NEE               0              0.0
PG                0              0.0
QQQ               0              0.0
SPY               0              0.0
TLT               0              0.0
UNH               0              0.0
V                 0              0.0
VNQ               0              0.0
VXUS              0              0.0
VZ                0              0.0
XOM               0              0.0

This table shows how many missing adjusted close prices each asset has which shows 0 missing values. Missing values need to be checked before calculating final returns because missing prices can create incorrect return values for model

In [9]:
# In case future missing data 
adj_close_clean = adj_close.dropna()

adj_close_clean.shape

(2010, 21)

In [10]:
print("Original rows:", adj_close.shape[0])
print("Clean rows:", adj_close_clean.shape[0])
print("Rows removed:", adj_close.shape[0] - adj_close_clean.shape[0])

Original rows: 2010
Clean rows: 2010
Rows removed: 0

For this first preprocessing version, rows with missing adjusted close prices are removed. This keeps all assets aligned on the same trading dates, 

This is important for calculating returns, correlations, and portfolio metrics.

In [11]:
daily_returns_clean = adj_close_clean.pct_change().dropna()

daily_returns_clean.head()

,AAPL,AGG,AMZN,CAT,GLD,JPM,KO,LLY,LMT,MSFT,...,PG,QQQ,SPY,TLT,UNH,V,VNQ,VXUS,VZ,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-03,-0.000174,0.000092,0.012775,0.001528,-0.002637,0.001019,-0.002196,0.005432,0.008381,0.004654,...,-0.001213,0.009717,0.006325,0.004781,0.010490,0.009955,-0.002903,0.006971,-0.020549,0.019640
2018-01-04,0.004645,-0.000641,0.004476,0.013734,0.005127,0.014325,0.014084,0.004463,0.017154,0.008801,...,0.007068,0.001750,0.004215,-0.000159,0.004340,0.003718,-0.017227,0.008307,0.003243,0.001384
2018-01-05,0.011385,-0.000641,0.016163,0.015805,-0.001036,-0.006419,-0.000217,0.012278,0.009060,0.012398,...,0.000658,0.010043,0.006664,-0.002855,0.019069,0.023949,0.000494,0.006694,-0.002281,-0.000806
2018-01-08,-0.003714,-0.000276,0.014425,0.025129,-0.000160,0.001477,-0.001519,-0.005083,-0.004611,0.001020,...,0.005261,0.003891,0.001829,-0.000637,-0.017357,0.004038,0.005182,-0.000512,-0.001715,0.004496
2018-01-09,-0.000114,-0.002752,0.004676,0.002409,-0.004628,0.005069,0.004999,-0.000813,0.007162,-0.000680,...,-0.007305,0.000061,0.002264,-0.013373,0.004983,-0.001927,-0.012888,0.000853,-0.003668,-0.004246

In [12]:
daily_returns_clean.shape

(2009, 21)

In [13]:
daily_returns_clean.describe()

,AAPL,AGG,AMZN,CAT,GLD,JPM,KO,LLY,LMT,MSFT,...,PG,QQQ,SPY,TLT,UNH,V,VNQ,VXUS,VZ,XOM
count,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,...,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000,2009.000000
mean,0.001140,0.000077,0.000914,0.000936,0.000623,0.000822,0.000413,0.001520,0.000442,0.001065,...,0.000415,0.000820,0.000605,-0.000018,0.000465,0.000722,0.000290,0.000324,0.000162,0.000538
std,0.019401,0.003669,0.021680,0.020035,0.009535,0.018298,0.012163,0.019741,0.015659,0.017861,...,0.012591,0.015153,0.012260,0.009923,0.019772,0.016307,0.014006,0.011224,0.012987,0.018996
min,-0.128647,-0.040010,-0.140494,-0.142822,-0.064269,-0.149649,-0.096725,-0.141364,-0.127616,-0.147390,...,-0.087373,-0.119788,-0.109424,-0.066682,-0.223797,-0.135472,-0.177277,-0.111318,-0.074978,-0.122248
25%,-0.007925,-0.001631,-0.010250,-0.009349,-0.004385,-0.007638,-0.005262,-0.007835,-0.005936,-0.007372,...,-0.005599,-0.005958,-0.004280,-0.005967,-0.007681,-0.006954,-0.006109,-0.005073,-0.005906,-0.009448
50%,0.001187,0.000177,0.001084,0.000780,0.000646,0.000872,0.000643,0.001662,0.000699,0.001254,...,0.000730,0.001365,0.000899,0.000167,0.000827,0.001423,0.000745,0.000887,0.000346,0.000481
75%,0.011071,0.001850,0.012258,0.011852,0.005667,0.009361,0.006276,0.010271,0.007668,0.010266,...,0.006882,0.008557,0.006519,0.005736,0.009269,0.008477,0.007230,0.006099,0.006632,0.010648
max,0.153288,0.023721,0.135359,0.116346,0.048530,0.180125,0.064796,0.156798,0.107280,0.142169,...,0.120090,0.120031,0.105019,0.075196,0.127989,0.138427,0.089966,0.083810,0.092705,0.126868

## Check for weird infinite or weird vals

In [14]:
np.isinf(daily_returns_clean).sum()

AAPL    0
AGG     0
AMZN    0
CAT     0
GLD     0
JPM     0
KO      0
LLY     0
LMT     0
MSFT    0
NEE     0
PG      0
QQQ     0
SPY     0
TLT     0
UNH     0
V       0
VNQ     0
VXUS    0
VZ      0
XOM     0
dtype: int64

In [15]:
daily_returns_clean.isna().sum()

AAPL    0
AGG     0
AMZN    0
CAT     0
GLD     0
JPM     0
KO      0
LLY     0
LMT     0
MSFT    0
NEE     0
PG      0
QQQ     0
SPY     0
TLT     0
UNH     0
V       0
VNQ     0
VXUS    0
VZ      0
XOM     0
dtype: int64

# Save Processed Cleaned Data

In [16]:
adj_close_clean.to_csv(PROCESSED_DATA_PATH / "yfinance_adjusted_close_clean.csv")
daily_returns_clean.to_csv(PROCESSED_DATA_PATH / "yfinance_daily_returns_clean.csv")

# High Level Processed Data Summary

In [17]:
TRADING_DAYS = 252

In [18]:
processed_summary = pd.DataFrame({
    "mean_daily_return": daily_returns_clean.mean(),
    "daily_volatility": daily_returns_clean.std(),
    "annualized_return": daily_returns_clean.mean() * TRADING_DAYS,
    "annualized_volatility": daily_returns_clean.std() * np.sqrt(TRADING_DAYS),
    "min_daily_return": daily_returns_clean.min(),
    "max_daily_return": daily_returns_clean.max()
})

In [19]:
processed_summary

,mean_daily_return,daily_volatility,annualized_return,annualized_volatility,min_daily_return,max_daily_return
AAPL,0.001140,0.019401,0.287326,0.307982,-0.128647,0.153288
AGG,0.000077,0.003669,0.019346,0.058242,-0.040010,0.023721
AMZN,0.000914,0.021680,0.230284,0.344154,-0.140494,0.135359
CAT,0.000936,0.020035,0.235961,0.318047,-0.142822,0.116346
GLD,0.000623,0.009535,0.156912,0.151369,-0.064269,0.048530
JPM,0.000822,0.018298,0.207217,0.290465,-0.149649,0.180125
KO,0.000413,0.012163,0.104066,0.193087,-0.096725,0.064796
LLY,0.001520,0.019741,0.383132,0.313381,-0.141364,0.156798
LMT,0.000442,0.015659,0.111428,0.248579,-0.127616,0.107280
MSFT,0.001065,0.017861,0.268446,0.283531,-0.147390,0.142169
NEE,0.000609,0.017092,0.153583,0.271335,-0.134171,0.136904
PG,0.000415,0.012591,0.104637,0.199871,-0.087373,0.120090
QQQ,0.000820,0.015153,0.206583,0.240550,-0.119788,0.120031
SPY,0.000605,0.012260,0.152411,0.194623,-0.109424,0.105019
TLT,-0.000018,0.009923,-0.004559,0.157517,-0.066682,0.075196
UNH,0.000465,0.019772,0.117255,0.313868,-0.223797,0.127989
V,0.000722,0.016307,0.181890,0.258870,-0.135472,0.138427
VNQ,0.000290,0.014006,0.073090,0.222342,-0.177277,0.089966
VXUS,0.000324,0.011224,0.081760,0.178175,-0.111318,0.083810
VZ,0.000162,0.012987,0.040855,0.206163,-0.074978,0.092705
XOM,0.000538,0.018996,0.135652,0.301556,-0.122248,0.126868

## Save to CSV

In [20]:
processed_summary.to_csv(PROCESSED_DATA_PATH / "yfinance_processed_summary_stats.csv")

# Final Summary

In this notebook it was focused on loading in raw adjusted close price data, checking missing vals, align the assets by date, calc clean daily returns, and save processed datasets.

### Files Created
- `data/processed/source_data/yfinance/yfinance_adjusted_close_clean.csv`
- `data/processed/source_data/yfinance/yfinance_daily_returns_clean.csv`
- `data/processed/source_data/yfinance/yfinance_processed_summary_stats.csv`